---
# see https://docs.google.com/spreadsheets/d/1W4H1IgDXKv24Sf7aWeqeAqxjKVj8EJB9giYN9obqPgU/edit#gid=493008265
ingressEgressThroughputPerSec: "2Mi"
totalMaxConnections: 100
maxDataRetentionSize: "60Gi"
maxPartitions: 100
maxDataRetentionPeriod: "P14D"
maxConnectionAttemptsPerSec: 100