# This file contains the configuration for cloud providers supported by KAS Fleet Manager
# KAS Fleet Manager will allow for Kafkas to be created using the cloud provider(s) and region(s) listed here.
# 
# supported_instance_type: This contains the list of Kafka instance types supported by the cloud provider and region. KAS Fleet Manager will not allow you
# to create any Kafka instances with types that is not listed here.
#   - Limits for each instance type can be set here (limit value: 0-n)
# 
#     Example configuration:
#     ...
#     - name: us-east-1
#       supported_instance_type:
#           standard:
#             limit: 5
#           developer: {}
#     ...
#     
#     With the above configuration, up to 5 'standard' Kafka instances can be created in the us-east-1 region. Since there is no region limit set for 'developer',
#     KAS Fleet Manager will allow creation of 'developer' Kafka instances in the us-east-1 region as long as a data plane cluster is available in this region 
#     (i.e. is schedulable, has remaining capacity and supports this Kafka instance type)
#     
#     Note: If manual scaling is enabled, please ensure that the limits you configure here matches/must not exceed the kafka_instance_limits of your data
#           plane clusters in the dataplane-cluster-configuration.yaml file
# 
---
supported_providers:
  - name: aws # name of the cloud provider
    default: true # only one default cloud provider is allowed
    regions:
      - name: us-east-1 # name of the region
        default: true # only one default region is allowed per cloud provider
        supported_instance_type:
          standard: {}
          developer: {}
