---
# A list of registered users given by their usernames irrespective whether they are under an organisation or not.
# If a user is not in this or in the `registered_users_per_organisation` list, only DEVELOPER kafka instances will be allowed.
# For now, this only supports RH service account.
# In the future it may support service accounts outside RH.
# The structure of registered service accounts is:
#       - username: is the account of the user. The username must be unique
#       - max_allowed_instances: is the maximum number of instances of a given instance_type/billing_model pair this user can create.
#         This value is used if `max_allowed_instances` field (inside `billing_model`) is 0 or omitted.
#         Defaults to the global value of `max-allowed-instances` which has different values for distinct environments.
#       - granted_quota: the configuration of the quota granted to the user.
#         If granted_quota is empty or is not defined, it will default to an array containing quota for `standard` instance.
#         The configuration is defined as follows:
#         - instance_type_id: the id of the instance type for which we are configuring the quota. This must match the IDs used in the KFM
#           `supported_instance_types` configuration.
#         - kafka_billing_models: the list of billing models that we are going to configure.
#           If `kafka_billing_models` is empty or is not defined, the default value will be used (a list containing only the "standard" billing model)
#           The set of accepted billing models, depends on the KafkaBillingModel configuration.
#           The content of this field is defined as follows:
#           - id: the id of the billing model we are going to configure. The set of valid IDs here is the set of the KafkaBillingModel IDs
#             available in the 'supported_billing_models' set per instance type in the 'supported_instance_types' configuration.
#           - max_allowed_instances: the number of instances of this type the user can create
#           - expiration_date: the date when the quota will expire (all instances with this billing model will be suspended). If not specified, there is no expiration
#             The date must comprise the offset from the UTC, using the following format: "YYYY-MM-DD {+,-}{HH:MM}".
#             Examples:
#             - CET: 2022-12-06 +01:00
#             - UTC: 2022-12-06 +00:00
registered_service_accounts:
  - username: testuser1@example.com
    max_allowed_instances: 3
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
          - id: enterprise
          - id: eval
  - username: testuser2@example.com
    max_allowed_instances: 2
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
          - id: enterprise
          - id: eval
  - username: testuser3@example.com
    max_allowed_instances: 2
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
          - id: enterprise
          - id: eval
  - username: testuser4@example.com
    max_allowed_instances: 2
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
          - id: enterprise
          - id: eval
  - username: testuser5@example.com
    max_allowed_instances: 2
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
          - id: enterprise
          - id: eval

# A list of registered users per organisation (see structure below). The list current contains known organisations - add yours if it is missing.
# If a user is not in this or in the `registered_service_accounts` list, only DEVELOPER kafka instances will be allowed.
# - "id": is the organisation id
# - "any_user": "any_user": Controls whether to allow all users to create standard kafka instances with this organisation if "registered_users" list is empty.
# - max_allowed_instances: is the maximum number of instances of a given instance_type/billing_model pair this user can create.
#   This value is used if `max_allowed_instances` field (inside `billing_model`) is 0 or omitted.
#   Defaults to the global value of `max-allowed-instances` which has different values for distinct environments.
# - granted_quota: the configuration of the quota granted to the user. The configuration is defined as follows:
#   - instance_type_id: the id of the instance type for which we are configuring the quota
#   - kafka_billing_models: the list of billing models that we are going to configure.
#     If `kafka_billing_models` is empty or is not defined, the default value will be used (a list containing only the "standard" billing model)
#     The set of accepted billing models, depends on the KafkaBillingModel configuration.
#     The content of this field is defined as follows:
#     - id: the id of the billing model we are going to configure. The set of valid IDs here is the set of the KafkaBillingModel IDs
#       available in the 'supported_billing_models' set per instance type in the 'supported_instance_types' configuration.
#     - max_allowed_instances: the number of instances of this type the user can create
#     - expiration_date: the date when the quota will expire (all instances with this billing model will be suspended). If not specified, there is no expiration
#       The date must comprise the offset from the UTC, using the following format: "YYYY-MM-DD {+,-}{HH:MM}".
#       Examples:
#       - CET: 2022-12-06 +01:00
#       - UTC: 2022-12-06 +00:00
registered_users_per_organisation:
    # The Control Plane team
  - id: 13640203
    any_user: true
    max_allowed_instances: 5
    registered_users: []
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
            max_allowed_instances: 5
          - id: marketplace
            max_allowed_instances: 5
          - id: enterprise
            max_allowed_instances: 5
          - id: eval  
    # The App SRE team
  - id: 12147054
    any_user: true
    max_allowed_instances: 1
    registered_users: []
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
            max_allowed_instances: 1
          - id: enterprise
            max_allowed_instances: 1
          - id: eval
    # The Kafka Instances team
  - id: 13639843
    any_user: true
    max_allowed_instances: 1
    registered_users: []
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
            max_allowed_instances: 1
          - id: enterprise
            max_allowed_instances: 1
          - id: eval
    # The MK Security team
  - id: 13785172
    any_user: true
    max_allowed_instances: 1
    registered_users: []
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
            max_allowed_instances: 1
          - id: enterprise
            max_allowed_instances: 1
          - id: eval
    # The Running the Service team
  - id: 13645369
    any_user: true
    max_allowed_instances: 3
    registered_users: []
    granted_quota:
      - instance_type_id: standard
        kafka_billing_models:
          - id: standard
            max_allowed_instances: 3
          - id: enterprise
            max_allowed_instances: 3
          - id: eval
